version: '3.8'

services:
  # TRAEFIK - traefik.localhost
  traefik:
    image: "traefik:v2.4"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.defaultRule=HostRegexp(`{_:{{ index .Labels \"com.docker.compose.service\" }}\\..*}`)"
    ports:
      - "${PUBLIC_PORT-80}:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: HostRegexp(`{_:traefik\..*}`)
      traefik.http.services.traefik.loadbalancer.server.port: 8080

  # Unsecure API
  unsecure:
    image:  sisakz/es2023-hu-ro-training-microservices
    ports:
      - 5002:5002
      - 5001:5001
      - 5000:5000
      - 5003:5003
      - 5004:5004
      - 5005:5005
      - 5006:5006

  # API - api.localhost
  api:
    build:
      context: module-c
      dockerfile: Dockerfile
    volumes:
      - ./module-c/app:/app/app
      - ./module-c/config:/app/config
      - ./module-c/database:/app/database
      - ./module-c/routes:/app/routes
      - ./module-c/storage:/app/storage
      - ./module-c/public:/app/public
      - ./module-c/bootstrap:/app/bootstrap
      - ./module-c/resources:/app/resources
    env_file:
      - module-c/.env
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: HostRegexp(`{_:api\..*}`)
      traefik.http.services.api.loadbalancer.server.port: 80